# Generated by Django 3.2.20 on 2023-08-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Contraseña'),
        ),
    ]
